name: 'reactive-commons-ci-cd'

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master
  
  release:
    types: [created]

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute jacocoTestReport and Sonar
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: ./gradlew test jacocoTestReport sonarqube
#        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
      - name: Build with Gradle
        run: ./gradlew build --refresh-dependencies --no-daemon --continue
#      - name: Push codeCoverage to Codecov
#        run: bash <(curl -s https://codecov.io/bash)

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Execute jacocoTestReport
#        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
      - name: Build with Gradle
        run: ./gradlew build --refresh-dependencies --no-daemon --continue
#      - name: Push codeCoverage to Codecov
#        run: bash <(curl -s https://codecov.io/bash)
      - name: Echo credentials
        run: echo "bintrayUser=${{secrets.BINTRAY_USER}}" >> gradle.properties
      - name: Echo credentials Key
        run: echo "bintrayApiKey=${{secrets.BINTRAY_KEY}}" >> gradle.properties && cat gradle.properties     
      - name: Publish plugin
        run: ./gradlew bintrayUpload
