name: 'reactive-commons-ci-cd'

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  release:
    types: [created]

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute build test jacocoTestReport and sonar analysis
        if: endsWith(github.REF, '/master') == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build test jacocoTestReport sonarqube --refresh-dependencies --no-daemon --continue
      - name: Execute build test jacocoTestReport pull request
        if: endsWith(github.REF, '/merge') == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build test jacocoTestReport --refresh-dependencies --no-daemon --continue

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Execute jacocoTestReport
#        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
      - name: Build with Gradle
        run: ./gradlew build asciidoctor --refresh-dependencies --no-daemon --continue
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: true
          prWoLabels: true
          issues: true
          issuesWoLabels: true
          stripGeneratorNotice: true
      - name: Push Docs and Changelog
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Automatic docs and changelog generation'
          force-add: 'true'
          files: CHANGELOG.md docs/
          name: ${{ github.actor }}
          email: ${{ github.actor }}@users.noreply.github.com
#      - name: Push codeCoverage to Codecov
#        run: bash <(curl -s https://codecov.io/bash)
      - name: Echo credentials
        run: echo "bintrayUser=${{secrets.BINTRAY_USER}}" >> gradle.properties
      - name: Echo credentials Key
        run: echo "bintrayApiKey=${{secrets.BINTRAY_KEY}}" >> gradle.properties && cat gradle.properties
      - name: Publish plugin
        run: ./gradlew bintrayUpload
